# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_book_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='classes',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.Classfication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classfication',
            name='name',
            field=models.CharField(default='yuan', max_length=32),
        ),
    ]
