# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170829_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='classes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Classfication'),
        ),
        migrations.AlterField(
            model_name='classfication',
            name='name',
            field=models.CharField(default='文学类', max_length=32),
        ),
    ]
